// let SHOPIFY_MULTIPASS_TOKEN="";
// let SHOPIFY_STORE_URL="";
// let WEBHOOK_APP_API_SECRET_KEY="";
// let NGROK_SERVER_URL="";
// let WEBHOOK_APP_ACCESS_TOKEN="";
// let REACT_SERVER_URL=""
// let PROXY_MAPPER_NAME="";
// export {SHOPIFY_MULTIPASS_TOKEN, SHOPIFY_STORE_URL};
// exports.credentials={
//     "SHOPIFY_MULTIPASS_TOKEN":SHOPIFY_MULTIPASS_TOKEN,
//     "SHOPIFY_STORE_URL":SHOPIFY_STORE_URL};

// exports.REACT_SERVER_URL=REACT_SERVER_URL;